# Generated by Django 4.0.3 on 2022-03-30 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="undefined", max_length=50)),
                ("intro", models.CharField(max_length=500)),
                (
                    "cover",
                    models.ImageField(blank=True, upload_to="static/photos/cover"),
                ),
                ("like", models.IntegerField(default=0)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.IntegerField(default=95434)),
                ("title", models.CharField(default="Untitled", max_length=20)),
                ("info", models.CharField(default="Uninfoed", max_length=100)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("photo", models.ImageField(upload_to="static/photos/photo")),
                ("gallery", models.ManyToManyField(to="gallery.gallery")),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, upload_to="static/photos/avatar"),
                ),
                ("admin", models.BooleanField(default=False)),
                (
                    "django_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo_Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("like", models.IntegerField(default=0)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gallery.photo"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gallery.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="photo",
            name="tag",
            field=models.ManyToManyField(to="gallery.tag"),
        ),
        migrations.AddField(
            model_name="photo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gallery.user"
            ),
        ),
        migrations.CreateModel(
            name="Gallery_Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("like", models.IntegerField(default=0)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gallery.gallery",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gallery.user"
                    ),
                ),
            ],
        ),
    ]
