# Generated by Django 4.0.3 on 2022-03-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo", name="like", field=models.IntegerField(default=0),
        ),
    ]
