# Generated by Django 4.0.3 on 2022-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="gallery", name="like",),
        migrations.AddField(
            model_name="gallery",
            name="like_user",
            field=models.ManyToManyField(to="gallery.user"),
        ),
        migrations.AddField(
            model_name="gallery_comment",
            name="like_user",
            field=models.ManyToManyField(
                related_name="like_user_gallery_comment", to="gallery.user"
            ),
        ),
        migrations.AddField(
            model_name="photo", name="like", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photo",
            name="like_user",
            field=models.ManyToManyField(
                related_name="like_user_photo", to="gallery.user"
            ),
        ),
        migrations.AddField(
            model_name="photo_comment",
            name="like_user",
            field=models.ManyToManyField(
                related_name="like_user_photo_comment", to="gallery.user"
            ),
        ),
    ]
