# Generated by Django 4.0.3 on 2022-04-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_photo_like"),
        ("gallery", "0002_remove_gallery_like_gallery_like_user_and_more"),
    ]

    operations = []
