# Generated by Django 4.0.3 on 2022-04-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_remove_gallery_like_gallery_like_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="tag",
            field=models.ManyToManyField(to="gallery.tag"),
        ),
    ]
