# Generated by Django 4.0.3 on 2022-04-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_gallery_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery", name="like", field=models.IntegerField(default=0),
        ),
    ]
