# Generated by Django 4.0.3 on 2022-04-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_gallery_tag"),
        ("gallery", "0003_merge_20220402_1858"),
    ]

    operations = []
