# Generated by Django 4.0.3 on 2022-04-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_gallery_like"),
        ("gallery", "0004_merge_0003_gallery_tag_0003_merge_20220402_1858"),
    ]

    operations = []
