# Generated by Django 4.0.2 on 2022-04-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_merge_20220405_2032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="like_user",
            field=models.ManyToManyField(to="gallery.User"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="tag",
            field=models.ManyToManyField(to="gallery.Tag"),
        ),
        migrations.AlterField(
            model_name="gallery_comment",
            name="like_user",
            field=models.ManyToManyField(
                related_name="like_user_gallery_comment", to="gallery.User"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="gallery",
            field=models.ManyToManyField(to="gallery.Gallery"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="like_user",
            field=models.ManyToManyField(
                related_name="like_user_photo", to="gallery.User"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="tag",
            field=models.ManyToManyField(to="gallery.Tag"),
        ),
        migrations.AlterField(
            model_name="photo_comment",
            name="like_user",
            field=models.ManyToManyField(
                related_name="like_user_photo_comment", to="gallery.User"
            ),
        ),
    ]
