# Generated by Django 4.0.3 on 2022-04-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_merge_20220406_1845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="cover",
            field=models.ImageField(
                blank=True,
                default="./static/test_photos/cover",
                upload_to="static/photos/cover",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                default="./static/test_photos/8513087.jpg",
                upload_to="static/photos/photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="./static/test_photos/test_avatar.jpeg",
                upload_to="static/photos/avatar",
            ),
        ),
    ]
