# Generated by Django 4.0.3 on 2022-04-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_alter_gallery_cover_alter_photo_photo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("is_admin", "This user is an admin"),
                    ("post_comments", "This user can post comments"),
                ]
            },
        ),
    ]
