# Generated by Django 4.0.2 on 2022-04-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_alter_gallery_like_user_alter_gallery_tag_and_more"),
        ("gallery", "0007_alter_user_options"),
    ]

    operations = []
