# Generated by Django 4.0.2 on 2022-04-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0008_merge_20220407_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery_comment",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gallery_comment",
            name="pub_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="gallery_comment",
            name="report_cnt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photo_comment",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="photo_comment",
            name="pub_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="photo_comment",
            name="report_cnt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user", name="cmt_cnt", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="report_cmt_cnt",
            field=models.IntegerField(default=0),
        ),
    ]
