# Generated by Django 3.2.5 on 2022-04-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0008_merge_20220407_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="operation",
            field=models.CharField(default="origin", max_length=100),
        ),
    ]
