# Generated by Django 3.2.5 on 2022-04-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0009_photo_operation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("is_admin", "This user is an admin"),
                    ("post_comments", "This user can post comments"),
                    ("is_alive", "This user is not killed"),
                ]
            },
        ),
    ]
