# Generated by Django 4.0.3 on 2022-04-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0009_gallery_comment_is_banned_gallery_comment_pub_date_and_more"),
        ("gallery", "0010_alter_user_options"),
    ]

    operations = []
