# Generated by Django 4.0.3 on 2022-04-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0011_merge_20220421_1328"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="layout",
            field=models.CharField(default="board", max_length=20),
        ),
    ]
