# Generated by Django 4.0.3 on 2022-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0014_auto_20220425_1900"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery", name="cmt_cnt", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photo", name="cmt_cnt", field=models.IntegerField(default=0),
        ),
    ]
