# Generated by Django 4.0.3 on 2022-04-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0011_merge_20220421_1100"),
        ("gallery", "0014_auto_20220425_1900"),
    ]

    operations = []
