# Generated by Django 2.2.3 on 2022-05-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0016_auto_20220430_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery_comment",
            name="report_user",
            field=models.ManyToManyField(
                related_name="report_user_gallery_comment", to="gallery.User"
            ),
        ),
        migrations.AddField(
            model_name="photo_comment",
            name="report_user",
            field=models.ManyToManyField(
                related_name="report_user_photo_comment", to="gallery.User"
            ),
        ),
    ]
