# Generated by Django 4.0.3 on 2022-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0018_alter_gallery_id_alter_gallery_comment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag", name="fixed", field=models.BooleanField(default=False),
        ),
    ]
