# Generated by Django 4.0.3 on 2022-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0019_tag_fixed"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo", name="order", field=models.IntegerField(default=0),
        ),
    ]
