# Generated by Django 4.0.3 on 2022-05-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0019_tag_fixed"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_length", models.IntegerField(default=0)),
            ],
        ),
    ]
