# Generated by Django 4.0.3 on 2022-05-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0020_fixqueue"),
        ("gallery", "0020_photo_order"),
    ]

    operations = []
