# Generated by Django 4.0.3 on 2022-05-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0021_merge_0020_fixqueue_0020_photo_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="gallery.user",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="like_user",
            field=models.ManyToManyField(
                related_name="like_user_gallery", to="gallery.user"
            ),
        ),
    ]
