# Generated by Django 4.0.3 on 2022-05-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0015_merge_20220428_1419"),
        ("gallery", "0023_alter_gallery_user"),
    ]

    operations = []
