# Generated by Django 4.0.3 on 2022-05-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0024_merge_20220514_1215"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_length", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=20)),
            ],
        ),
    ]
