# Generated by Django 4.0.3 on 2022-05-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0025_checkqueue"),
    ]

    operations = [
        migrations.RemoveField(model_name="checkqueue", name="name",),
    ]
